apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJXbVZ5WjFwbGREcG5hSEJmV0c1MFNWUmpOMVoyYTJkTGIySk1ZV04wWmxaRVRGTTROR3BIVGprek1XcFBkRlZzIgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson

