{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
       imagePullSecrets:
        - name: regcred
      containers:
        - name: events-service
          image: "{{ .Values.eventsService.image.repository }}:{{ .Values.eventsService.image.tag }}"
          imagePullPolicy: {{ .Values.eventsService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.eventsService.service.targetPort }}
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
            - secretRef:
                name: cinemaabyss-secrets
          resources:
            {{- toYaml .Values.eventsService.resources | nindent 12 }}т
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: events-service
  ports:
  - port: {{ .Values.eventsService.service.port }}
    targetPort: {{ .Values.eventsService.service.targetPort }}
  type: {{ .Values.eventsService.service.type }}
{{- end }}
